### ISSUE TITLE
bug(@vtmn/css): enhancement needs to be done for Tabs component

### ISSUE THREAD

**Issue by Mig-l** [Decathlon/vitamin-web#1067]
- The icons do not take the colour of the link as well as the focus: 

![image](https://user-images.githubusercontent.com/5746252/159731993-eb32dd22-09b8-4d65-af6f-1fb271024fdf.png)

To fix add `color: inherit; ` for small and medium :

![image](https://user-images.githubusercontent.com/5746252/159733946-56b79427-b956-42c5-bf54-aec94fc5e423.png)

- There is an alignment problem when mixing with icon, badge or just text: 

![image](https://user-images.githubusercontent.com/5746252/159733021-77a21d2e-bc28-4cfa-a9c1-264ca87dced4.png)

- There is no active status for the tabs (not focus)

**Comment by lauthieb** [comment]
Hi @Mig-l,
Thanks! I close your PR because:

- For the first point, it is fixed: https://github.com/Decathlon/vitamin-web/commit/f510e433f1c269260d1251d37c9cb9ea296c13de
- For the second, we don't have this problem here on `@vtmn/css` showcase: http://localhost:6006/?path=/story/components-navigation-tabs--overview
- For the third, it is fixed: https://github.com/Decathlon/vitamin-web/commit/f510e433f1c269260d1251d37c9cb9ea296c13de

**Comment by Tlahey** [comment]
@lauthieb for the second point it's because the `VtmnIcon` have a default variant. So, it apply `--vtmn-semantic-color_content-primary`
