### ISSUE TITLE
feat(@vtmn/react): `VtmnRadioButton` and `VtmnCheckbox` should be able to be used in uncontrolled mode

### ISSUE THREAD

**Issue by atissedredecathlon** [Decathlon/vitamin-web#1174]
If I want to use these components in uncontrolled mode, I get an error in the console because the logic always uses the "checked" property : 

![image](https://user-images.githubusercontent.com/94351553/172444012-8601fb9e-af9f-492d-9801-6f79743c1b8d.png)

In controlled mode, I have to manage the state of each of my components. 

Even if this is the "React way" to do this, it is not always desirable as it is sometimes simpler and more efficient to manage the values with a form, at submit time. 

To be perfectly clear, here is a very simple example of implementation of what I'm referring as "uncontrolled mode" :

```
<form
  onSubmit={(e) => {
    e.preventDefault();
    console.log((e.target as HTMLFormElement).gcu.checked) // true or false --> we get the value here
  }}
>
  <input type="checkbox" defaultChecked={false} name="gcu" />
  <button>Submit</button>
</form>
```

IMO, all of the Vtmn React components should be usable in both controlled and uncontrolled modes. 

My current workaround requires me to set the `checked` property to `null`, and I have to ignore the issue that TypeScript raises from doing this : 

```
<VtmnCheckbox
  identifier="country"
  name="country"
  labelText="Le client est bien domicilié en France"
  defaultValue="f"
  required
  // @ts-ignore
  checked={null}
/>
```

**Comment by GaspardMathon** [comment]
Hi @atissedredecathlon, thanks for raising this issue. We will investigate as soon as possible :)

**Comment by astahmer** [comment]
related: having forwardRef around components would ease the use of form libs (such as [react-hook-form](https://react-hook-form.com/)) that relies on ref rather than controlled state (and thus avoid useless re-renders)

**Comment by lauthieb** [comment]
Hi @atissedredecathlon, I understand completely your request.
As the React library is maintained by the community, can you please create a Pull Request in order to propose us a solution that will stay compatible for our current consumers?
Fill free to ping me if you want to discuss in a videoconference or ask questions here. I can help you onboard inside vitamin-web.
@astahmer thanks for your advice.
Thanks a lot.

**Comment by atissedredecathlon** [comment]
Hi @lauthieb, unfortunately I don't have the time to draft a PR, but if that can help, here are some good examples of checkbox components, which can be used in both modes, from 2 of the most popular UI components libraries. 

These 2 libraries are known to respect good UX and accessibility practices, I believe they would be solid bases of inspiration on which to build robust components. 

Though honestly I don't know if it would be possible to make these changes without any breaking changes.

- Radix UI checkbox : 
https://github.com/radix-ui/primitives/blob/main/packages/react/checkbox/src/Checkbox.tsx

- Chakra UI checkbox : 
https://github.com/chakra-ui/chakra-ui/blob/main/packages/checkbox/src/checkbox.tsx

**Comment by lauthieb** [comment]
Hi @atissedredecathlon,

Thanks for your answer and examples.
As React library of Vitamin is built by the community (because of budget/scope reasons for the Vitamin core team), I'll let this issue with the badge "need help" and I hope someone will contribute.

Thanks again and sorry if `VtmnRadioButton` & `VtmnCheckbox` are not able to be used in uncontrolled mode for now.

Laurent

**Comment by lauthieb** [comment]
Hi @atissedredecathlon,
Finally, I've just pushed a commit that resolves your proposition: https://github.com/Decathlon/vitamin-web/commit/44625044ab8409c115503622c694470305298b7a
Thanks again :)
