### ISSUE TITLE
feat: make the dropdown accessible

### ISSUE THREAD

**Issue by M4gie** [Decathlon/vitamin-web#1207]
**Is your request related to a problem? Please describe.**
We are currently using the dropdown component with the svelte library and we are facing some accessibilities issues.

**A clear and concise description of what the problem is.**
We can't select a choice in the list with the `enter` key.

**Describe the solution you'd like**
We should be able to only use the keyboard to select a value in the dropdown

I'm available to work on this issue 👍

**Comment by lauthieb** [comment]
Hi @M4gie, when do you think you will work on this? Thanks a lot.

**Comment by M4gie** [comment]
Hey @lauthieb, I will work on it next week 😉

**Comment by lauthieb** [comment]
Hey @M4gie, nice thanks a lot!

**Comment by SRegnaultD** [comment]
I made some tests with a multiple select, the a11y is more logic with it since it's native but we can't style it. If we want to keep our current style we will need to keep our current solution with inputs. Manually modifying the a11y of the current solution could bring more a11y issues as we will need to handle it on all browsers and devices.

**Comment by lauthieb** [comment]
Thanks @SRegnaultD for your message and conclusion. So, I close this issue.
Thanks again for your suggestions and challenges.
