### ISSUE TITLE
bug: failed to parse source map on project using React with Typescript and Vtmn Library for React

### ISSUE THREAD

**Issue by jdeca-decat** [Decathlon/vitamin-web#1322]
**Describe the bug**
When I use "npm run build" on my project using React Typescript and Vtmn Library for React, I've got warnings (view image) : "failed to parse source map..."
![vtmn-problem-build](https://user-images.githubusercontent.com/107050404/210386909-b082a68f-bc40-4695-805e-c2bee51a65f3.png)
A solution consist to add "GENERATE_SOURCEMAP=false" to temporarily avoid this problem, to the command line "build" in the package.json, but I would like to find a cleaner solution because "today's warnings will be tomorrow's errors" !

**Steps to reproduce**
    1. Create a React Typescript project: "npx create-react-app [nameApp] --template typescript"
    2. Install Vtmn Library for React "npm install @vtmn/react"
    3. Create a simple page with a Vtmn Component
    4. Build your code and see warnings

**Version affected**
@react: 18.2.0
@typescript: 4.9.4
@vtmn/react: 0.57.0
@react-scripts: 5.0.1
@eslint: 8.31.0

**Comment by jdeca-decat** [comment]
It seem that the error does not come from vitamin-web -> (https://github.com/facebook/create-react-app/pull/11752)
Waiting for a resolution from Facebook...

**Comment by thibault-mahe** [comment]
Hi @jdeca-decat ! Thanks for reporting this issue.
I was able to replicate the concern on my side indeed.

I don't think the problem is with CRA, the PR you mentioned only asks for the possibility to override the warnings. But if the warnings are present it's probably for a good reason, or we shouldn't use source maps (to be discussed).

The issue that the warnings indicate here is that our packages distribute maps that reference sources that are not present. And indeed we don't export our sources in our packages, so the mapping can't work. To use your exemple : 

- `./node_modules/@vtmn/react/dist/index.js` uses the distributed `./node_modules/@vtmn/react/dist/index.js.map` to map between the production files and the original Typescript source files.
- `index.js.map` try to map a file to `node_modules/@vtmn/react/src/components/overlays/VtmnTooltip/VtmnTooltip.tsx` but we do not distribute original `@vtmn/react/src` in our package, so the reference is missing
- Warning: Failed to parse source map / no such file or directory / etc.

I need to go back and discuss with my team on this one, to understand what were the initial intentions here and measure what the consequences would be of either removing the mappings or adding our sources to the packages (cc @lauthieb). If this problem exists it is probably because the mapping is not relevant and was never needed / integrated in a debugging strategy. My recommendation would be to stop generating source maps. I'll get back to you.

Thanks again!

**Comment by lauthieb** [comment]
@thibault-mahe you're right!
As source maps could be useful for consumers to debug their code when using Vitamin's React library. I think it could be nice to check what Chakra UI, Material UI and other famous React UI libraries do regarding source maps (& export of their sources).
