### ISSUE TITLE
bug(@vtmn/react): `VtmnDropdownItem` component doesn't display any content

### ISSUE THREAD

**Issue by jdeca-decat** [Decathlon/vitamin-web#1401]
**Describe the bug**
When I add items to VtmnDropdown like in the React showcase, nothing appear..
![Screenshot from 2023-03-24 12-44-41](https://user-images.githubusercontent.com/107050404/227513784-91180c7e-59d9-4b56-9155-e9a4353fafe5.png)
![Screenshot from 2023-03-24 12-43-50](https://user-images.githubusercontent.com/107050404/227513787-40c78a30-1d8d-46c7-b5fb-41a3677b3932.png)

**Steps to reproduce**
- Install React
- install Vtmn package for React
- add VtmnDropdownItem component to your VtmnDropdown as children

**Expected behavior**
VtmnDropdownItem should be able to display their content, like in MUI Item Select

**Version affected**
@react: 18.2.0
@vtmn/react: 0.67.0

**Comment by lauthieb** [comment]
Thanks @jdeca-decat for this issue.
As the `@vtmn/react` is a community library, I hope someone will take this issue to help you.
If you want, feel free to contribute also! We are there to help you if needed regarding launching & contributing on the vitamin-web stack.

**Comment by 0x2A-git** [comment]
Hi @jdeca-decat,

I've tried to reproduce your setup in a CRA project and tested it on both Firefox & Chrome but I'm not able to reproduce it.

Code : 

```jsx
<VtmnDropdown
  id="foo"
  summary={'10'}
  onChange={(value: string) => {
    console.log(value)
  }}
>
  <VtmnDropdownItem id="item-1">10</VtmnDropdownItem>

  <VtmnDropdownItem id="item-2">20</VtmnDropdownItem>

  <VtmnDropdownItem id="item-3">30</VtmnDropdownItem>
</VtmnDropdown>
```
Result : 

![image](https://user-images.githubusercontent.com/20931885/227770302-235ebe2a-2d60-458c-b515-202d38d773dd.png)

The only 'issue' that I've encountered is the 'value' parameter being set to undefined which is the expected behavior given that my VtmnDropdownItem do not have a value attribute. 

Could the VtmnDropdown component be wrapped inside another component that would prevent its children from being displayed ? :thinking:

**Comment by 0x2A-git** [comment]
Hi @jdeca-decat,

I've tried to reproduce your setup in a CRA project and tested it on both Firefox & Chrome but I'm not able to reproduce it.

Code :

<VtmnDropdown
  id="foo"
  summary={'10'}
  onChange={(value: string) => {
    console.log(value)
  }}
>
  <VtmnDropdownItem id="item-1">10</VtmnDropdownItem>

  <VtmnDropdownItem id="item-2">20</VtmnDropdownItem>

  <VtmnDropdownItem id="item-3">30</VtmnDropdownItem>
</VtmnDropdown>

Result :

![image](https://user-images.githubusercontent.com/20931885/227771241-6057c712-1556-475b-87ec-208cdfbeef34.png)

The only 'issue' that I've encountered is the 'value' parameter being set to undefined which is the expected behavior given that my VtmnDropdownItem do not have a value attribute.

Could the VtmnDropdown component be wrapped inside another component that would prevent its children from being displayed ? thinking
