### ISSUE TITLE
bug: Missing icons in React package

### ISSUE THREAD

**Issue by thibault-mahe** [Decathlon/vitamin-web#1422]
**Describe the bug**

Some icons seems to be present in the Svelte package but missing in the React package, like the `tools` (`line` and `fill`) icon.

![image](https://user-images.githubusercontent.com/5102622/233279241-626376ac-5489-41cd-8931-64e761ad6609.png)

Some potential other missing ones:

```
.vtmx-tools-fill:before {
    content: "\f2a3";
}
.vtmx-tools-line:before {
    content: "\f2a4";
}
.vtmx-train-fill:before {
    content: "\f2a5";
}
.vtmx-train-line:before {
    content: "\f2a6";
}
.vtmx-trophy-fill:before {
    content: "\f2a7";
}
.vtmx-trophy-line:before {
    content: "\f2a8";
}
```
@llecle for more details

**Steps to reproduce**

**Expected behavior**

**Browsers affected**

**Version affected**

**Comment by lauthieb** [comment]
Hello,

Sorry, but there's no bug from our side. After investigating, `@vtmn/react` & `@vtmn/svelte` depends on the same package `@vtmn/icons`.

https://github.com/Decathlon/vitamin-web/blob/b4287d01f2011fcef69ef2f616a922fcbb53033b/packages/sources/react/package.json#L36

https://github.com/Decathlon/vitamin-web/blob/b4287d01f2011fcef69ef2f616a922fcbb53033b/packages/sources/svelte/package.json#L68

And after verification, all the icons that you mentioned are also present in our React showcase:

![CleanShot 2023-04-20 at 09 00 14](https://user-images.githubusercontent.com/9600228/233286170-17b0ab3c-14be-4a65-86f6-1c1211d00f23.png)

Example here: https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/story/guidelines-iconography-vtmnicon--overview&args=size:32;value:tools-line

@llecle That's why it's not from our side. You probably still have version an older version of `@vtmn/icons` in your `package-lock.json`, I encourage you to upgrade to our latest version (or at least, the one requested by our latest `@vtmn/react` package).

Therefore, I close this issue. Thanks.
