### ISSUE TITLE
question(@vtmn/css-button): text break

### ISSUE THREAD

**Issue by bastienterrier** [Decathlon/vitamin-web#562]
Hello,

I have some issue using the `.vtmn-btn` class from `@vtmn/css-button` lib. This class has the following property `white-space: nowrap;` that causes text content to be cut:

![image](https://user-images.githubusercontent.com/25296454/132227829-ebf93083-8a82-4546-84bd-f5c07a78362c.png)

I fix it using `white-space: normal;` but I have to do it for all buttons...

![image](https://user-images.githubusercontent.com/25296454/132228337-e4b8f14a-ae0d-4a13-982c-8a4be5861459.png)

Is this behavior intentional?

Thank's for your answer!

**Comment by lauthieb** [comment]
Hi @bastienterrier, thanks for your question! Yes it's an intentional behavior because we have a "DON'T" regarding the usage of more than one line for a button:

![Capture d’écran 2021-09-07 à 17 57 44](https://user-images.githubusercontent.com/9600228/132375955-35e5186d-c169-4b94-aa73-34e9c8367fd0.png)

Cf: https://www.decathlon.design/726f8c765/p/8008f8-button/b/57e0e1

That's why by default we respect guidelines from designers. But, we understand that sometimes (and it depends on the language), it could be difficult to have a single line for button labels, so that's why you have the possibility to add `white-space: normal` as you did. If you want, we can create a CSS utility class inside Vitamin like `.vtmn-btn--multiline`?

**Comment by bastienterrier** [comment]
Thanks for your answer!

I totally understand and a `.vtmn-btn--multiline` class would be great to fit this particular need. :)

**Comment by lauthieb** [comment]
Thanks @bastienterrier, here is the PR: https://github.com/Decathlon/vitamin-web/pull/578

**Comment by bastienterrier** [comment]
Great, thank you @lauthieb !
