### ISSUE TITLE
bug(@vtmn/react): Typescript warnings in the console when `yarn build` 

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#650]
# Bug Report

Hello,
There are Typescript warnings in the console when `yarn build` on `@vtmn/react` package.

<img width="1114" alt="Capture d’écran 2021-10-04 à 12 37 14" src="https://user-images.githubusercontent.com/9600228/135837422-96fec379-a47b-45b4-ae57-c325a3a6985a.png">

**Steps to reproduce**

`yarn && cd packages/sources/react && yarn build`

Thanks!

**Comment by Wizyma** [comment]
Hey @lauthieb !

So i checked a bit there is some parts that are a bit tricky, for example for the `textarea` you are trying to mix the event onChange from the `textarea` and the `input` wich are not the of the same types. 

The best way to change that would be to have a `VtmnInput` and a `VtmnTextArea` to split up the differences and avoid having conditions like this for two different component and conditionnal types. 

Or the other way around could look up like something 
```typescript
import * as React from 'react';
import clsx from 'clsx';

import '@vtmn/css-text-input/dist/index-with-vars.css';
import { VtmnIcon } from '../VtmnIcon';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';

export interface BaseVtmnTextInputProps {
  /**
   * ID of the input
   * @type {string}
   */
  identifier: string;

  /**
   * Label text linked to the input
   * @type {string}
   */
  labelText?: string;

  /**
   * Helper text to help the user
   * @type {string}
   * @defaultValue undefined and therefore not displayed by default
   */
  helperText?: string;

  /**
   * Placeholder
   * @type {string}
   */
  placeholder?: string;

  /**
   * Icon to display inside text input
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  icon?: VitamixId;

  /**
   * Is a TextArea
   * @type {boolean}
   * @defaultValue false (Input)
   */
  multiline?: boolean;

  /**
   * Whether input is successful or not
   * @type {boolean}
   * @defaultValue false
   */
  valid?: boolean;

  /**
   * Whether input is in error or not
   * @type {boolean}
   * @defaultValue false
   */
  error?: boolean;
}

type VtmnTextInputProps<T> = T extends { multiline: true }
  ? React.ComponentPropsWithoutRef<'textarea'> & T
  : React.ComponentPropsWithoutRef<'input'> & T;

export const VtmnTextInput = ({
  className,
  disabled = false,
  error = false,
  helperText,
  icon = undefined,
  identifier,
  labelText,
  multiline = false,
  placeholder,
  valid = false,
  ...props
}: VtmnTextInputProps<BaseVtmnTextInputProps>) => {
  return (
    <React.Fragment>
      {labelText && (
        <label className="vtmn-text-input_label" htmlFor={identifier}>
          {labelText}
        </label>
      )}
      {multiline ? (
        <textarea
          className={clsx('vtmn-text-input', className, {
            'vtmn-text-input--error': error,
            'vtmn-text-input--valid': valid,
          })}
          id={identifier}
          placeholder={placeholder}
          disabled={disabled}
          {...(props as React.ComponentPropsWithoutRef<'textarea'>)}
        />
      ) : (
        <div className="vtmn-text-input_container">
          <input
            className={clsx(
              'vtmn-text-input',
              className,
              { 'vtmn-text-input--valid': valid && !disabled },
              { 'vtmn-text-input--error': error && !disabled },
            )}
            id={identifier}
            type="text"
            placeholder={placeholder}
            disabled={disabled}
            {...props}
          />
          {icon && <VtmnIcon value={icon} size={20} />}
        </div>
      )}
      {helperText && (
        <p
          className={clsx('vtmn-text-input_helper-text', className, {
            'vtmn-text-input_helper-text--error': error,
          })}>
          {helperText}
        </p>
      )}
    </React.Fragment>
  );
};

export default React.memo(VtmnTextInput);
```

As you can see i wrote a conditionnal type  wich kinda allow us to have two different types but on the props of the textarea we still need to cast the type because the magic of typescript have some limits :D 
```typescript
type VtmnTextInputProps<T> = T extends { multiline: true }
  ? React.ComponentPropsWithoutRef<'textarea'> & T
  : React.ComponentPropsWithoutRef<'input'> & T;
```

And for some others Components you just basicly need an `Omit` utility type on some property as you are using names that comes from the base `HtmlElement` type ie: 
In `VtmnToggleProps` you are using the size property to handle the classname but `size` is also a property from the input so the TS compiler is warning about setting a `string` to a type that should be a `number` 

You could change that by changing the name of the prop or adding the `Omit` utility 
```typescript
export interface VtmnToggleProps extends Omit<React.ComponentPropsWithoutRef<'input'>, 'size'> { ...YOUR_PROPS }
```

**Comment by Wizyma** [comment]
I can work on this when i have time (it's a bit complicated this month for me) otherwise to resolve this issue my comment should help the one who would like to work on it.

**Comment by lauthieb** [comment]
Hi @Wizyma, I would like to thank you a lot for you detailed answer. Your learnt me some key points about TypeScript.
As you can see on #651, @blemoine has already resolved this issue and it seems that he used the same solution that you have proposed just after.
Feel free if you still want to improve this!
Have a nice day :)
Laurent
