### ISSUE TITLE
bug(@vtmn/css-select): disabled state should update the label color

### ISSUE THREAD

**Issue by Thibault-DECAT** [Decathlon/vitamin-web#832]
# Bug Report

**Bug report**

According to Design system use case, a Select component with disabled state should update the label color, actually the color is not updated.

**Current behavior**

<img width="361" alt="Capture d’écran 2021-12-29 à 14 51 56" src="https://user-images.githubusercontent.com/45452064/147669119-3092d183-57cf-441f-b398-e0dbe62c570a.png">

**Expected behavior**

<img width="361" alt="Capture d’écran 2021-12-29 à 14 51 37" src="https://user-images.githubusercontent.com/45452064/147669141-45a196a6-0b03-4b6e-a1a8-136ff840ff47.png">

**Steps to reproduce**

install an use @vtmn/css-select

**Related code**

```
.vtmn-select_container select:disabled + label {
  opacity: var(--vtmn-opacity_disabled-state);
  cursor: not-allowed;
}
```

The selector should be updated 'cause in the `DOM` `label` is before `select` and not after.

**Browsers affected**

all

**Versions**

- @vtmn/css-select: v0.3.4

**Comment by lauthieb** [comment]
Hi @Thibault-DECAT, thanks for reporting this.
You're completely right. Unfortunately for this major version `v0.x.x`, it will be hard to find a solution that will not cause breaking changes for people that don't change any piece of code after updating our package because we will probably need to change the markup.
Too bad that `:has` keyword is not ready, part of CSS4 specification in order to easily target previous sibling... Source: https://stackoverflow.com/a/15503444
Do you have an idea about solving this problem without any breaking change? 
If not, in your opinion, what could be the best way to resolve this with breaking change?
@crotru @jleveugle @thollander @xavhan @gabbloquet @GaspardMathon could be nice to have your opinion ❤️ 
Thanks again @Thibault-DECAT!

**Comment by crotru** [comment]
Will have a proper look later but, as a side note, 
`:has` just shipped in Safari Technology Preview. It might not be that far...

**Comment by lauthieb** [comment]
> Hi @Thibault-DECAT, thanks for reporting this.
> 
> You're completely right. Unfortunately for this major version `v0.x.x`, it will be hard to find a solution that will not cause breaking changes for people that don't change any piece of code after updating our package because we will probably need to change the markup.
> 
> Too bad that `:has` keyword is not ready, part of CSS4 specification in order to easily target previous sibling... Source: https://stackoverflow.com/a/15503444
> 
> Do you have an idea about solving this problem without any breaking change? If not, in your opinion, what could be the best way to resolve this with breaking change?
> 
> @crotru @jleveugle @thollander @xavhan @gabbloquet @GaspardMathon could be nice to have your opinion ❤️ Thanks again @Thibault-DECAT!

As I said just above, we will take this into account only for our next major version. Thanks for your understanding.
