### ISSUE TITLE
bug(@vtmn/css): `theme.screens` values

### ISSUE THREAD

**Issue by crotru** [Decathlon/vitamin-web#834]
# Bug Report

**Bug report**

**Current behavior**
There is a confusion in the breakpoint naming.
In order to target breakpoint matching "greater than mobile" we now need yo use `gt-tablet`

![image](https://user-images.githubusercontent.com/22882255/147687945-797991c6-ae05-4ee5-8b2b-a1541c4aeb1d.png)

Tablet is 600 to 900, so `gt-tablet` should match `> 900` and not `> 600`

Same goes for the other `gt-xxx`

We won't use it right now because it will induce regression as soon as it's fixed, 
and therefore we are unable to build our app mobile-first
(so a correction asap would be dope ^^)

**Expected behavior**

We should be able to target viewport greater than 600px with a `gt-mobile` name

**Related code**

[tailwind-preset.js](https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/presets/tailwind/tailwind-preset.js)

```
screens: {
      mobile: { max: '599px' },
      tablet: { min: '600px', max: '899px' },
      'gt-tablet': { min: '600px' },
      'lt-small-desktop': { max: '899px' },
      'small-desktop': { min: '900px', max: '1199px' },
      'gt-small-desktop': { min: '900px' },
      'lt-medium-desktop': { max: '1199px' },
      'medium-desktop': { min: '1200px', max: '1799px' },
      'gt-medium-desktop': { min: '1200px' },
      'lt-large-desktop': { max: '1799px' },
      'large-desktop': { min: '1800px' },
 },
```

**Comment by lauthieb** [comment]
Hi @crotru,

Thanks for requesting this. I understand the problem you just mentioned.

When we chose this (#558), we built `gt-tablet` like "tablet + the rest that are greater". 
I think we could have done better with `goe-tablet` like "greater or equals tablet" 😢

I understand your changes suggestions but unfortunately, we can't because it would be a big problem for our existing consumers (more than 1K lines of code are using these utility classes at `dktunited` private organization).

It's a thing that we will change in our next major release `v1.x.x` with the new redesign for sure and respect that Tailwind is built around mobile-first methodology so we will only keep "mobile", "tablet", "small-desktop", "medium-desktop" and "large-desktop" with just `min` values.

Sorry again.

**Comment by lauthieb** [comment]
> Hi @crotru,
> 
> Thanks for requesting this. I understand the problem you just mentioned.
> 
> When we chose this (#558), we built `gt-tablet` like "tablet + the rest that are greater". I think we could have done better with `goe-tablet` like "greater or equals tablet" 😢
> 
> I understand your changes suggestions but unfortunately, we can't because it would be a big problem for our existing consumers (more than 1K lines of code are using these utility classes at `dktunited` private organization).
> 
> It's a thing that we will change in our next major release `v1.x.x` with the new redesign for sure and respect that Tailwind is built around mobile-first methodology so we will only keep "mobile", "tablet", "small-desktop", "medium-desktop" and "large-desktop" with just `min` values.
> 
> Sorry again.

As I said just above, we will take this into account only for our next major version. Thanks for your understanding.
