### ISSUE TITLE
bug(@vtmn/react): `VtmnTooltip` is cropped

### ISSUE THREAD

**Issue by astahmer** [Decathlon/vitamin-web#971]
**Describe the bug**
- Cropped tooltip:
![image](https://user-images.githubusercontent.com/90684087/152569847-8616365e-4ff9-4ce7-a115-3db0987a3134.png)

_Originally posted by @Charles-Babin in https://github.com/dktunited/mybusiness/issues/2328#issuecomment-1030169452_

**Steps to reproduce**

- have a container div wrapping a <table> element, set a `max-height` + `overflow: auto` so the table can be scrolled inside the container
- have a tooltip anywhere inside that table near the container div's borders
- hover the tooltip and see that it's cropped

**Expected behavior**

not being cropped
this might not be feasible using just css, usually solved using [Portal](https://reactjs.org/docs/portals.html)

**Browsers affected**

    - Chrome
**Version affected**

"@vtmn/css-tooltip": "^0.6.4",

**Comment by GaspardMathon** [comment]
Thanks @astahmer for your issue. 
I checked on my side and the overflow container is blocking the display of the tooltip, but thats seems normal to me as the role of the overflow is to hide everything out of the container.

I have two solutions : 

- I can make the tooltip as wide as the element it wraps, and make the text wrap too so the the tooltip will stay consistent within its element.
- I can't make the tooltip only overflow of the parent container with `overflow: hidden`, for me it's you you have to choose the right `position` variant of the tooltip according the context. So that means applying a position `bottom` when the text is at the top of the page/container and a position `right` when your element is near the left of your page/container.

I need to ask my designer team about the change for the first point.

**Comment by GaspardMathon** [comment]
From a design POV, the tooltip must remain on one line only and be as wide as it contains text (but we suggest to write short text only in tooltip). However, if you need to have a bigger kind of tooltip, you can use a `popover` component instead of the `tooltip`.

**Comment by astahmer** [comment]
made a basic reproduction repo + solution using portal as mentionned in the original post
https://github.com/astahmer/vtmn-tooltip-portal

https://codesandbox.io/s/github/astahmer/vtmn-tooltip-portal
it seems vitamin is hiding tooltips with breakpoints so you need to open the preview in a new window to see the cropped case

**Comment by lauthieb** [comment]
Hi @astahmer, do you think that we need CSS modifications from our side?

**Comment by lauthieb** [comment]
Okay thanks a lot @astahmer

**Comment by astahmer** [comment]
weird closing this issue, that means you won't address it ? i did file this as a bug to `vtmn/react`, and not `vtmn/css` ?

**Comment by lauthieb** [comment]
OH okay, I reopen if React contributor can help us.

**Comment by lauthieb** [comment]
Thanks @astahmer.
I hope someone will make a PR, sorry React is a community lib so we don't have any time to make this.

**Comment by astahmer** [comment]
hey @lauthieb , kinda hard to reproduce without a [codesandbox](https://codesandbox.io/)/[stackblitz](https://stackblitz.com/) or at least the story commited

a [quick google search](https://www.google.com/search?q=target+container+is+not+a+dom+element&rlz=1C5CHFA_enFR994FR995&oq=target+container+is+&aqs=chrome.0.0i512j69i57j0i512l8.1846j0j7&sourceid=chrome&ie=UTF-8) [leads to](https://bobbyhadz.com/blog/react-createroot-target-container-not-dom-element):

> To solve the "createRoot(...): Target container is not a DOM element" error, make sure that the ID you are using to select the element is the same ID that you have specified in your index.html file and place the react script below the code that declares the div element.

looking at the current state of [the PR](https://github.com/Decathlon/vitamin-web/pull/1200/files) this looks like this won't work as expected as btw, you still need a [positioning library](https://floating-ui.com/docs/react-dom) in your implementation like [here](https://github.com/astahmer/vtmn-tooltip-portal/blob/main/src/components/VtmnTooltipWithPortal.tsx) or [here](https://github.com/dktunited/mybusiness/blob/ab9190b3664f87133e610e033495575e13d1c3ac/src/components/VtmnTooltipWithPortal.tsx)

**Comment by lauthieb** [comment]
Hi @astahmer, thanks for your explanations.

**Comment by thibault-mahe** [comment]
Hi @NourcheneBenali,
unfortunately not yet. As it is discussed here: 
- it seems that there is no need to make modification from our side on the @vtmn/css package since it is not a css issue ;
- the tooltip component need to be rewritten with a positioning library. Currently the most common one seems to be [@floating-ui/dom](https://github.com/floating-ui/floating-ui/tree/master/packages/dom) (Vanilla) or [@floating-ui/react-dom](https://github.com/floating-ui/floating-ui/tree/master/packages/react-dom) (React specific) as @astahmer suggested ;
- this React package is a community lib we can't actively maintain for now so we hope someone could make a PR to help you on this issue.

We are currently working on new ways to help Vitamin users contribute and consume our components though, including a rework of some of this components. But for now we can only leave this issue open and remain available if anyone wishes to propose a solution.

Sorry about that!
